OUTPUT_DIR: "trained_models/overfit"
INPUT:
  MIN_SIZE_TRAIN: (1500,)
  MIN_SIZE_TEST: 1500
  MAX_SIZE_TRAIN: 2100
  MAX_SIZE_TEST: 2100
  HORIZONTAL_FLIP_PROB_TRAIN: 0.0 # has to be a float
  VERTICAL_FLIP_PROB_TRAIN: 0.0
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2500
    PRE_NMS_TOP_N_TEST: 2500
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 500
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 14
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("census_coco_overfit",)
  TEST: ("census_coco_overfit",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 180000)
  MAX_ITER: 250000
  CHECKPOINT_PERIOD: 100
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 8
  DETECTIONS_PER_IMG: 500
