OUTPUT_DIR: "trained_models/census_20191106_faster_big_imgs"
INPUT:
  MIN_SIZE_TRAIN: (1500,)
  MIN_SIZE_TEST: 1500
  MAX_SIZE_TRAIN: 2500
  MAX_SIZE_TEST: 2500
  HORIZONTAL_FLIP_PROB_TRAIN: 0.0 # has to be a float
  VERTICAL_FLIP_PROB_TRAIN: 0.0
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 500
    PRE_NMS_TOP_N_TEST: 500
    POST_NMS_TOP_N_TRAIN: 500
    POST_NMS_TOP_N_TEST: 500
    FPN_POST_NMS_TOP_N_TEST: 500
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 500
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 14
DATASETS:
  TRAIN: ("census_coco_train",)
  TEST: ("census_coco_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (10000, 30000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 8
  DETECTIONS_PER_IMG: 500
